import { useEffect, useMemo, useState } from 'react'
import { ACCOUNT_TYPES, TRANSACTION_TYPES, createTransaction, effectiveBalances, generateTransactionTimestamp, parsePkrAmount } from '../lib/budget.js'
import EditTransactionModal from './EditTransactionModal.jsx'

const money = (value) => `PKR ${Number(value || 0).toLocaleString(undefined, { maximumFractionDigits: 2 })}`
const localDateTime = (value) => { const date = new Date(value); return Number.isNaN(date.getTime()) ? 'Unknown date' : date.toLocaleString() }

function TransactionModal({ type, onClose, onSubmit }) {
  const [amount, setAmount] = useState(''); const [reason, setReason] = useState(''); const [source, setSource] = useState(''); const [timestamp] = useState(() => generateTransactionTimestamp()); const [error, setError] = useState('')
  useEffect(() => { const fn = (e) => e.key === 'Escape' && onClose(); document.addEventListener('keydown', fn); return () => document.removeEventListener('keydown', fn) }, [onClose])
  const label = type === TRANSACTION_TYPES.INCOME ? 'Money Earned' : 'Money Used'
  const submit = (e) => { e.preventDefault(); if (parsePkrAmount(amount) === null) return setError('Enter a non-negative amount.'); if (!source) return setError('Choose cash or bank as the source.'); try { onSubmit(createTransaction({ type, amount, reason, source, timestamp })); onClose() } catch (err) { setError(err.message) } }
  return <div className="fixed inset-0 z-10 flex items-center justify-center bg-slate-900/50 p-4" role="presentation" onMouseDown={(e) => e.target === e.currentTarget && onClose()}><div className="w-full max-w-md rounded-lg bg-white p-6 shadow-xl" role="dialog" aria-modal="true"><h2 className="text-xl font-semibold">Add {label}</h2><form className="mt-4 space-y-4" onSubmit={submit}><label className="block text-sm font-medium">Amount (PKR)<input className="mt-1 w-full rounded border p-2" type="number" min="0" step="any" value={amount} onChange={(e) => setAmount(e.target.value)} required /></label><label className="block text-sm font-medium">Reason<input className="mt-1 w-full rounded border p-2" value={reason} onChange={(e) => setReason(e.target.value)} /></label><fieldset><legend className="text-sm font-medium">Source</legend><div className="flex gap-4">{Object.entries({ Cash: ACCOUNT_TYPES.CASH, Bank: ACCOUNT_TYPES.BANK }).map(([n, v]) => <label key={v}><input type="radio" name="add-source" value={v} checked={source === v} onChange={(e) => setSource(e.target.value)} /> {n}</label>)}</div></fieldset>{error && <p className="text-sm text-red-600">{error}</p>}<div className="flex justify-end gap-2"><button type="button" className="rounded border px-4 py-2" onClick={onClose}>Cancel</button><button className="rounded bg-slate-900 px-4 py-2 text-white">Add {label}</button></div></form></div></div>
}

export default function Dashboard({ setup = {}, transactions = [], onTransactionSubmit, onAddTransaction, onTransactionUpdate, onTransactionDelete, dateRange = { start: '', end: '' }, onDateRangeChange }) {
  const [modalType, setModalType] = useState(null); const [editing, setEditing] = useState(null)
  const balances = useMemo(() => effectiveBalances(setup, transactions), [setup, transactions]); const submitTransaction = onTransactionSubmit || onAddTransaction || (() => {}); const loans = Array.isArray(setup.loans) ? setup.loans : []
  const history = [...transactions].sort((a, b) => new Date(b.timestamp) - new Date(a.timestamp)).filter((t) => { const day = new Date(t.timestamp).toISOString().slice(0, 10); return (!dateRange.start || day >= dateRange.start) && (!dateRange.end || day <= dateRange.end) })
  return <section className="mt-8 space-y-6" aria-label="Budget dashboard"><div className="grid gap-4 sm:grid-cols-3"><div className="rounded-lg bg-white p-5 shadow"><p>Cash balance</p><p className="text-2xl font-bold">{money(balances.cash)}</p></div><div className="rounded-lg bg-white p-5 shadow"><p>Bank balance</p><p className="text-2xl font-bold">{money(balances.bank)}</p></div><div className="rounded-lg bg-white p-5 shadow"><p>Total Available Amount</p><p className="text-2xl font-bold">{money(balances.cash + balances.bank)}</p></div></div><div className="rounded-lg bg-white p-5 shadow"><h2 className="text-lg font-semibold">Setup and loans</h2><p>Starting cash: {money(setup.cash)} · Starting bank: {money(setup.bank ?? setup.online)}</p><p>Loans: {money(loans.reduce((s, l) => s + (parsePkrAmount(l.amount) ?? 0), 0))}</p></div><div className="flex gap-3"><button className="rounded bg-slate-900 px-4 py-2 text-white" onClick={() => setModalType(TRANSACTION_TYPES.EXPENSE)}>Add Money Used</button><button className="rounded bg-emerald-700 px-4 py-2 text-white" onClick={() => setModalType(TRANSACTION_TYPES.INCOME)}>Add Money Earned</button></div><div className="rounded-lg bg-white p-5 shadow"><h2 className="text-lg font-semibold">Transaction history</h2><div className="mt-3 flex gap-3"><label>From <input type="date" value={dateRange.start} onChange={(e) => onDateRangeChange?.({ ...dateRange, start: e.target.value })} /></label><label>To <input type="date" value={dateRange.end} onChange={(e) => onDateRangeChange?.({ ...dateRange, end: e.target.value })} /></label></div>{history.length === 0 ? <p className="mt-3">No transactions yet.</p> : <ul className="divide-y">{history.map((t) => <li key={t.id} className="py-3"><div className="flex justify-between"><span>{money(t.amount)} · {t.type === TRANSACTION_TYPES.INCOME || t.type === 'earned' ? 'Earned' : 'Used'}</span><time>{localDateTime(t.timestamp)}</time></div><p>{t.source === ACCOUNT_TYPES.BANK ? 'Bank' : 'Cash'}{t.reason ? ` · ${t.reason}` : ''}</p><button onClick={() => setEditing(t)}>Edit</button> <button onClick={() => onTransactionDelete?.(t.id)}>Delete</button></li>)}</ul>}</div>{modalType && <TransactionModal type={modalType} onClose={() => setModalType(null)} onSubmit={submitTransaction} />}{editing && <EditTransactionModal transaction={editing} onClose={() => setEditing(null)} onSubmit={onTransactionUpdate} />}</section>
}
